# jtv shell history integration for zsh.
# Generated by `jtv shell-init zsh`; source with `eval "$(jtv shell-init zsh)"`.

function _jtv_import_native_history() {
  emulate -L zsh
  local sink=$1 entry

  # The Rust side also validates this endpoint before writing. Recheck it here
  # so an integration failure cannot turn record text into shell input.
  [[ -f $sink && ! -L $sink && -O $sink ]] || return 0

  while IFS= read -r entry || [[ -n $entry ]]; do
    [[ -n $entry ]] && print -s -- "$entry"
  done < "$sink"

  # `print -s` updates the live history used by recall and
  # zsh-autosuggestions. Append through zsh itself when persistence is enabled;
  # never parse or rewrite HISTFILE directly.
  if [[ -n ${HISTFILE-} && ${SAVEHIST:-0} -gt 0 ]]; then
    fc -AI "$HISTFILE" 2>/dev/null || true
  fi
}

function jtv() {
  emulate -L zsh
  local sink history_session jtv_status signal_status=0

  sink=$(command mktemp "${TMPDIR:-/tmp}/jtv-history.XXXXXXXX") 2>/dev/null
  if [[ -z $sink ]]; then
    command jtv "$@"
    return $?
  fi
  command chmod 600 "$sink" 2>/dev/null || {
    command rm -f -- "$sink"
    command jtv "$@"
    return $?
  }

  history_session=${sink:t}
  typeset -x JTV_HISTORY_SINK=$sink
  typeset -x JTV_SHELL_INTEGRATION=zsh
  typeset -x JTV_HISTORY_PROTOCOL=1
  typeset -x JTV_HISTORY_SESSION=$history_session
  if [[ -n ${ZSH_AUTOSUGGEST_STRATEGY+x} ]]; then
    typeset -x JTV_ZSH_AUTOSUGGESTIONS=1
  fi
  if [[ -n ${ATUIN_SESSION-} ]] && (( $+commands[atuin] )) \
      && [[ -x ${commands[atuin]} ]]; then
    typeset -x JTV_ATUIN_BIN=${commands[atuin]}
  fi
  trap 'signal_status=129' HUP
  trap 'signal_status=130' INT
  trap 'signal_status=143' TERM
  {
    command jtv "$@"
    jtv_status=$?
    (( signal_status )) && jtv_status=$signal_status
  } always {
    trap - HUP INT TERM
    if (( ! signal_status )); then
      _jtv_import_native_history "$sink"
    fi
    command rm -f -- "$sink" 2>/dev/null
  }
  return $jtv_status
}
